function love.conf(t)
    t.version = "0.10.1"                -- The LÖVE version this game was made for (string)

    t.window.title = "3DBalls"     -- The window title (string)

    t.window.width = 800                  -- The window width (number)
    t.window.height = 600                  -- The window height (number)
    t.window.borderless = false            -- Remove all border visuals from the window (boolean)
    t.window.resizable = false             -- Let the window be user-resizable (boolean)
    t.window.fullscreen = false            -- Enable fullscreen (boolean)
    t.window.vsync = true                  -- Enable vertical sync (boolean)
    t.window.msaa = 0                      -- The number of samples to use with multi-sampled antialiasing (number)

    t.modules.audio = false              -- Enable the audio module (boolean)
    t.modules.event = true              -- Enable the event module (boolean)
    t.modules.graphics = true           -- Enable the graphics module (boolean)
    t.modules.image = false              -- Enable the image module (boolean)
    t.modules.joystick = false           -- Enable the joystick module (boolean)
    t.modules.keyboard = true           -- Enable the keyboard module (boolean)
    t.modules.math = false               -- Enable the math module (boolean)
    t.modules.mouse = false              -- Enable the mouse module (boolean)
    t.modules.physics = false            -- Enable the physics module (boolean)
    t.modules.sound = false              -- Enable the sound module (boolean)
    t.modules.system = true             -- Enable the system module (boolean)
    t.modules.timer = true              -- Enable the timer module (boolean), Disabling it will result 0 delta time in love.update
    t.modules.touch = false              -- Enable the touch module (boolean)
    t.modules.video = false              -- Enable the video module (boolean)
    t.modules.window = true             -- Enable the window module (boolean)
    t.modules.thread = false             -- Enable the thread module (boolean)
end
